try{
    console.log(shuvo);
}
catch(error){
    console.log("inside catch");
    console.log(error);
}
finally{
    console.log("Finally we did it ");
}
console.log(1000);
console.log(1000);
console.log(1000);
console.log(1000);
console.log(1000);
console.log(1000);
console.log(1000);
console.log(1000);
console.log(1000);
console.log(1000);
console.log(1000);
